name: Deploy to GitHub Pages

# Trigger on pushes to main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read       # checkout
      pages: write         # deploy to Pages
      id-token: write      # for deploy-pages auth
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: read
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
